# Generated by Django 5.1.6 on 2025-02-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rqe',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
