# Generated by Django 5.1.6 on 2025-03-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_active_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compliant_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
