# Generated by Django 5.1.6 on 2025-12-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='compliant_since',
        ),
    ]
