# Generated by Django 5.1.6 on 2026-07-24 00:45
import unicodedata

from django.db import migrations, models

def normalize_name(value):
    value = unicodedata.normalize("NFKD", value or "")

    value = "".join(
        character
        for character in value
        if not unicodedata.combining(character)
    )

    return " ".join(value.casefold().split())


def populate_search_names(apps, schema_editor):
    User = apps.get_model("core", "User")
    database = schema_editor.connection.alias

    users = list(
        User.objects.using(database).all().only(
            "id",
            "name",
            "search_name",
        )
    )

    for user in users:
        user.search_name = normalize_name(user.name)

    if users:
        User.objects.using(database).bulk_update(
            users,
            ["search_name"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_compliant_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=512),
        ),
        migrations.RunPython(
            populate_search_names,
            reverse_code=migrations.RunPython.noop,
        ),    
    ]
