# Generated by Django 5.1.9 on 2025-09-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_donationrequest_donee_donationrequest_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='end_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='start_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
