# Generated by Django 5.1.9 on 2025-09-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_alter_holiday_unique_together'),
        ('user_requests', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('donation', 'Donation'), ('exchange', 'Exchange'), ('include', 'Include'), ('exclude', 'Exclude')], max_length=20)),
                ('start_hour', models.IntegerField(blank=True, null=True)),
                ('end_hour', models.IntegerField(blank=True, null=True)),
                ('donee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
                ('requestee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_responded', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='shifts.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DonationRequest',
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['requester', 'is_open', 'created_at'], name='user_reques_request_781173_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['responder', 'is_approved', 'created_at'], name='user_reques_respond_b3087b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['request_type', 'created_at'], name='user_reques_request_9b796e_idx'),
        ),
    ]
