# Generated by Django 5.1.9 on 2025-09-23 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_alter_holiday_unique_together'),
        ('user_requests', '0005_userrequest_delete_donationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('requester', 'request_type', 'shift'), name='uniq_open_request_per_requester_type_shift'),
        ),
    ]
