# Generated by Django 5.1.9 on 2025-09-23 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_alter_holiday_unique_together'),
        ('user_requests', '0006_userrequest_uniq_open_request_per_requester_type_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrequest',
            name='uniq_open_request_per_requester_type_shift',
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('requester', 'request_type', 'shift', 'start_hour', 'end_hour'), name='uniq_open_request_per_requester_type_shift'),
        ),
    ]
