# Generated by Django 5.1.6 on 2025-10-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0008_remove_notification_user_reques_receive_6e20ec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('action', 'Action'), ('info', 'Info'), ('cancel', 'Cancel'), ('error', 'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('donation', 'Doação'), ('exchange', 'Troca'), ('include', 'Incluir'), ('exclude', 'Excluir')], max_length=20),
        ),
    ]
