# Generated by Django 5.1.6 on 2025-10-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_alter_holiday_unique_together'),
        ('user_requests', '0009_alter_notification_kind_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludeRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.center')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.month')),
                ('user_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='include_data', to='user_requests.userrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['center', 'month', 'day'], name='user_reques_center__ef7ba2_idx')],
            },
        ),
    ]
