# Generated by Django 5.1.6 on 2025-10-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0011_vacationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='vacationrequest',
            old_name='leave_type',
            new_name='request_type',
        ),
    ]
