# Generated by Django 5.1.6 on 2025-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0012_alter_vacationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='request_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('sick', 'Sick Leave')], max_length=20),
        ),
    ]
