# Generated by Django 5.1.6 on 2026-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0013_alter_vacationrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='audience',
            field=models.CharField(blank=True, choices=[('individual', 'Specific user'), ('admins', 'Any admin'), ('all_users', 'All users')], max_length=20, null=True),
        ),
    ]
