# Generated by Django 5.1.6 on 2026-04-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0015_populate_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='audience',
            field=models.CharField(choices=[('individual', 'Specific user'), ('admins', 'Any admin'), ('all_users', 'All users')], default='individual', max_length=20),
        ),
    ]
