# Generated by Django 5.1.6 on 2026-07-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0016_alter_userrequest_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('action', 'Action'), ('info', 'Info'), ('cancel', 'Cancel'), ('error', 'Error'), ('mass_action', 'Mass Action')], max_length=20),
        ),
    ]
