# Generated by Django 5.1.6 on 2026-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0017_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
