# Generated by Django 5.1.6 on 2026-07-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0018_userrequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
