# Generated by Django 5.1.6 on 2026-07-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0019_notification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
