# Generated by Django 5.1.6 on 2026-03-17 03:39

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('shifts', '0011_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('synthetic', 'Synthetic'), ('detailed', 'Detailed')], max_length=20)),
                ('file', models.FileField(upload_to=finance.models.upload_document_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='shifts.month')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
