# Generated by Django 5.1.6 on 2026-06-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financecategory_financesource_financeentry_and_more'),
        ('shifts', '0011_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.month')),
            ],
            options={
                'ordering': ['order', 'label'],
                'unique_together': {('month', 'code')},
            },
        ),
    ]
