# Generated by Django 5.1.6 on 2026-07-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financeconstant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Uploaded document', 'verbose_name_plural': 'Uploaded documents'},
        ),
    ]
