# Generated by Django 5.1.6 on 2026-07-30 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_uploadeddocument_options'),
        ('shifts', '0011_alter_holiday_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalFinancialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('original', 'Original hospital file'), ('coop', 'Cooperative version')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_financial_batches', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_financial_batches', to='shifts.month')),
                ('source_batch', models.ForeignKey(blank=True, help_text='Original hospital batch from which this version was generated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_batches', to='finance.hospitalfinancialbatch')),
                ('uploaded_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_batches', to='finance.uploadeddocument')),
            ],
            options={
                'ordering': ['-month__year', '-month__number', 'batch_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='HospitalFinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_plan_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Convênio')),
                ('procedure_description', models.CharField(blank=True, max_length=500, verbose_name='Descrição Procedimento')),
                ('provider_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Prestador')),
                ('transfer_description', models.CharField(blank=True, max_length=500, verbose_name='Descrição Repasse')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('row_number', models.PositiveIntegerField(blank=True, help_text='Original row number in the imported spreadsheet.', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.hospitalfinancialbatch')),
                ('source_entry', models.ForeignKey(blank=True, help_text='Original hospital entry corresponding to this cooperative entry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_entries', to='finance.hospitalfinancialentry')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='hospitalfinancialbatch',
            constraint=models.UniqueConstraint(fields=('month', 'batch_type', 'version'), name='unique_financial_batch_version'),
        ),
        migrations.AddConstraint(
            model_name='hospitalfinancialentry',
            constraint=models.UniqueConstraint(condition=models.Q(('row_number__isnull', False)), fields=('batch', 'row_number'), name='unique_row_number_per_financial_batch'),
        ),
    ]
