# Generated by Django 5.1.6 on 2026-08-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_hospitalfinancialbatch_hospitalfinancialentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalfinancialentry',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_financial_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalfinancialentry',
            name='match_status',
            field=models.CharField(choices=[('matched', 'Matched automatically'), ('manual', 'Matched manually'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20),
        ),
    ]
