# Generated by Django 5.1.6 on 2025-10-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_alter_holiday_unique_together'),
        ('vacations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('sick', 'Sick Leave')], default='regular', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplianceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Compliant'), ('N', 'Non-compliant'), ('U', 'Unknown')], default='U', max_length=1)),
                ('rule_version', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='system', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_histories', to='shifts.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'month'], name='vacations_c_user_id_a72a05_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='unique_user_month')],
            },
        ),
    ]
