# Generated by Django 5.1.6 on 2026-01-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_alter_vacation_vacation_type_compliancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overridden', 'Overridden')], default='pending', max_length=20),
        ),
    ]
