STR_DAY = 26
END_DAY = 25

MORNING_START, MORNING_END = 7, 13
AFTERNOON_START, AFTERNOON_END = 13, 19
CINDERELLA_START, CINDERELLA_END = 19, 1
VAMPIRE_START, VAMPIRE_END = 1, 6

HOUR_RANGE = [x for x in range(MORNING_START, 24)] + [x for x in range(0, VAMPIRE_END + 1)]

SHIFT_CODES = ['dn', 'd', 'm', 't', 'n', 'c', 'v']
SHIFTS_MAP = {
    'dn': (MORNING_START, VAMPIRE_END),
    'dc': (MORNING_START, CINDERELLA_END),
    'd': (MORNING_START, AFTERNOON_END),
    'n': (CINDERELLA_START, VAMPIRE_END),
    'm': (MORNING_START, MORNING_END),
    't': (AFTERNOON_START, AFTERNOON_END),
    'c': (CINDERELLA_START, CINDERELLA_END),
    'v': (VAMPIRE_START, VAMPIRE_END),
    #  'tn': (AFTERNOON_START, VAMPIRE_END),
    }

DIAS_SEMANA = ["SEGUNDA", "TERÇA", "QUARTA", "QUINTA", "SEXTA", "SABADO", "DOMINGO"]

LEADER = {'name': "DR. VICTOR HUGO MARCASSA", 'crm': 5078}
