MORNING_START, MORNING_END = 7, 12
AFTERNOON_START, AFTERNOON_END = 13, 18
CINDERELLA_START, CINDERELLA_END = 19, 0
VAMPIRE_START, VAMPIRE_END = 1, 6

SHIFTS_MAP = {
    'dn': (MORNING_START, VAMPIRE_END),
    'dc': (MORNING_START, CINDERELLA_END),
    'd': (MORNING_START, AFTERNOON_END),
    'n': (CINDERELLA_START, VAMPIRE_END),
    'm': (MORNING_START, MORNING_END),
    't': (AFTERNOON_START, AFTERNOON_END),
    'c': (CINDERELLA_START, CINDERELLA_END),
    'v': (VAMPIRE_START, VAMPIRE_END),
    #  'tn': (AFTERNOON_START, VAMPIRE_END),
    }

DIAS_SEMANA = ["SEGUNDA", "TERÇA", "QUARTA", "QUINTA", "SEXTA", "SABADO", "DOMINGO"]
