FINANCE_GRID_COLUMNS = [
    {
        "key": "user_name",
        "label": "ANESTESIOLOGISTA",
        "category": "",
        "editable": False,
        "kind": "text",
    },
    {
        "key": "crm",
        "label": "CRM",
        "category": "",
        "editable": False,
        "kind": "text",
    },

    {
        "key": "adm_hours_additional",
        "category": "ADM",
        "subcategory": "Horas",
        "label": "adicionais",
        "editable": True,
        "entry_type": "debit",
        "category_code": "adm",
        "source": "personnel",
    },

    {
        "key": "vacation_hours_rotine",
        "category": "FÉRIAS",
        "subcategory": "Horas",
        "label": "Rot",
        "editable": True,
        "entry_type": "debit",
        "category_code": "vacation",
        "source": "personnel",
    },
    {
        "key": "vacation_hours_urgent",
        "category": "FÉRIAS",
        "subcategory": "Horas",
        "label": "Urg",
        "editable": True,
        "entry_type": "debit",
        "category_code": "vacation",
        "source": "personnel",
    },

    {
        "key": "individual_particular_consult",
        "category": "INDIVIDUAL",
        "subcategory": "Partic",
        "label": "Cons",
        "editable": True,
        "entry_type": "credit",
        "category_code": "individual",
        "source": "client",
    },
    {
        "key": "individual_sus_ambulatoryconsult",
        "category": "INDIVIDUAL",
        "subcategory": "SUS",
        "label": "Cons Amb",
        "editable": True,
        "entry_type": "credit",
        "category_code": "individual",
        "source": "client",
    },

    {
        "key": "eco_particular_direct",
        "category": "R. ECO",
        "subcategory": "Partic",
        "label": "Direto",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_eco",
        "source": "eco",
    },
    {
        "key": "eco_unimed_coops",
        "category": "R. ECO",
        "subcategory": "Unimed",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_eco",
        "source": "eco",
    },
    {
        "key": "eco_copan_coops",
        "category": "R. ECO",
        "subcategory": "Copan",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_eco",
        "source": "eco",
    },

    {
        "key": "huem_particular_direct",
        "category": "R. HUEM",
        "subcategory": "Partic",
        "label": "Direto",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_huem",
        "source": "huem",
    },
    {
        "key": "huem_unimed_coops",
        "category": "R. HUEM",
        "subcategory": "Unimed",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_huem",
        "source": "huem",
    },
    {
        "key": "huem_coopan_coops",
        "category": "R. HUEM",
        "subcategory": "Copan",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_huem",
        "source": "huem",
    },

    {
        "key": "rp_huem_particular_proc",
        "category": "RP. HUEM",
        "subcategory": "Partic",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_convenios_proc",
        "category": "RP. HUEM",
        "subcategory": "Convênios",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_Ambulatory_proc",
        "category": "RP. HUEM",
        "subcategory": "Ambu",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_aih_proc",
        "category": "RP. HUEM",
        "subcategory": "AIH",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_sum_huemreport",
        "category": "RP. HUEM",
        "subcategory": "SOMA",
        "label": "Relat Huem",
        "editable": False,
        "kind": "hours",
        "source": "huem",
    },

    # Protected Hours columns (calculated from shifts/appointments, not editable)
    {
        "key": "inhours_huem_routine_ccg",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_ccg",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_cco",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_cco",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_ccq",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_ccq",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_sadt",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_sadt",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },

    {
        "key": "inhours_eco_routine_eco",
        "category": "HRS ECO",
        "subcategory": "ROT",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_eco",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },

    # Unprotected extra columns
    {
        "key": "credits_credits_debits",
        "category": "CRÉDITOS",
        "subcategory": "(+)CRÉDITOS",
        "label": "(-)DÉBITOS",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits",
        "source": "internal",
    },
    {
        "key": "credits_vacation_aid",
        "category": "CRÉDITOS",
        "subcategory": "FÉRIAS &",
        "label": "AUXÍLIOS",
        "editable": True,
        "entry_type": "debit",
        "category_code": "credits",
        "source": "internal",
    },
    {
        "key": "credits_adm_additional",
        "category": "CRÉDITOS",
        "subcategory": "ADM",
        "label": "ADICIONAIS",
        "editable": True,
        "entry_type": "debit",
        "category_code": "credits",
        "source": "internal",
    },
    {
        "key": "credits_cash_eco",
        "category": "CRÉDITOS",
        "subcategory": "EM MOEDA",
        "label": "ECO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits",
        "source": "internal",
    },

    {
        "key": "adjustments_routine_urgency_ccg",
        "category": "AJUSTES",
        "subcategory": "ROT + URG",
        "label": "CCG",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_urgency_cco",
        "category": "AJUSTES",
        "subcategory": "ROT + URG",
        "label": "CCO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_urgency_ccq",
        "category": "AJUSTES",
        "subcategory": "ROT + URG",
        "label": "CCQ",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_urgency_sadt",
        "category": "AJUSTES",
        "subcategory": "ROT + URG",
        "label": "SADT",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_urgency_eco",
        "category": "AJUSTES",
        "subcategory": "ROT + URG",
        "label": "ECO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
]