FINANCE_GRID_COLUMNS = [
    {
        "key": "user_name",
        "label": "ANESTESIOLOGISTA",
        "group": "",
        "editable": False,
        "kind": "text",
    },
    {
        "key": "crm",
        "label": "CRM",
        "group": "",
        "editable": False,
        "kind": "text",
    },

    {
        "key": "adm_hours_additional",
        "group": "ADM",
        "subgroup": "Horas",
        "label": "adicionais",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adm_hours_additional",
    },

    {
        "key": "vacation_hours_rotine",
        "group": "FÉRIAS",
        "subgroup": "Horas",
        "label": "Rot",
        "editable": True,
        "entry_type": "credit",
        "category_code": "vacation_hours_rotine",
    },
    {
        "key": "vacation_hours_urgent",
        "group": "FÉRIAS",
        "subgroup": "Horas",
        "label": "Urg",
        "editable": True,
        "entry_type": "credit",
        "category_code": "vacation_hours_urgent",
    },

    {
        "key": "individual_particular_consult",
        "group": "INDIVIDUAL",
        "subgroup": "Partic",
        "label": "Cons",
        "editable": True,
        "entry_type": "credit",
        "category_code": "individual_particular_consult",
    },
    {
        "key": "individual_sus_ambulatoryconsult",
        "group": "INDIVIDUAL",
        "subgroup": "SUS",
        "label": "Cons Amb",
        "editable": True,
        "entry_type": "credit",
        "category_code": "individual_sus_ambulatoryconsult",
    },

    {
        "key": "eco_particular_direct",
        "group": "R. ECO",
        "subgroup": "Partic",
        "label": "Direto",
        "editable": True,
        "entry_type": "credit",
        "category_code": "eco_particular_direct",
    },
    {
        "key": "eco_unimed_coops",
        "group": "R. ECO",
        "subgroup": "Unimed",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "eco_unimed_coops",
    },
    {
        "key": "eco_copan_coops",
        "group": "R. ECO",
        "subgroup": "Copan",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "eco_copan_coops",
    },

    {
        "key": "huem_particular_direct",
        "group": "R. HUEM",
        "subgroup": "Partic",
        "label": "Direto",
        "editable": True,
        "entry_type": "credit",
        "category_code": "huem_particular_direct",
    },
    {
        "key": "huem_unimed_coops",
        "group": "R. HUEM",
        "subgroup": "Unimed",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "huem_unimed_coops",
    },
    {
        "key": "huem_coopan_coops",
        "group": "R. HUEM",
        "subgroup": "Copan",
        "label": "Cooperados",
        "editable": True,
        "entry_type": "credit",
        "category_code": "huem_coopan_coops",
    },

    {
        "key": "rp_huem_particular_proc",
        "group": "RP. HUEM",
        "subgroup": "Partic",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "rp_huem_particular_proc",
    },
    {
        "key": "rp_huem_convenios_proc",
        "group": "RP. HUEM",
        "subgroup": "Convênios",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "rp_huem_convenios_proc",
    },
    {
        "key": "rp_huem_Ambulatory_proc",
        "group": "RP. HUEM",
        "subgroup": "Ambu",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "rp_huem_Ambulatory_proc",
    },
    {
        "key": "rp_huem_aih_proc",
        "group": "RP. HUEM",
        "subgroup": "AIH",
        "label": "Proc",
        "editable": True,
        "entry_type": "credit",
        "category_code": "rp_huem_aih_proc",
    },
    {
        "key": "rp_huem_sum_huemreport",
        "group": "RP. HUEM",
        "subgroup": "SOMA",
        "label": "Relat Huem",
        "editable": False,
        "kind": "hours",
    },

    # Protected Hours columns (calculated from shifts/appointments, not editable)
    {
        "key": "inhours_huem_routine_ccg",
        "group": "HRS HUEM",
        "subgroup": "ROT",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_ccg",
        "group": "HRS HUEM",
        "subgroup": "URG",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_cco",
        "group": "HRS HUEM",
        "subgroup": "ROT",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_cco",
        "group": "HRS HUEM",
        "subgroup": "URG",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_ccq",
        "group": "HRS HUEM",
        "subgroup": "ROT",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_ccq",
        "group": "HRS HUEM",
        "subgroup": "URG",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_sadt",
        "group": "HRS HUEM",
        "subgroup": "ROT",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_sadt",
        "group": "HRS HUEM",
        "subgroup": "URG",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },

    {
        "key": "inhours_eco_routine_eco",
        "group": "HRS ECO",
        "subgroup": "ROT",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_urgency_eco",
        "group": "HRS HUEM",
        "subgroup": "URG",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },

    # Unprotected extra columns
    {
        "key": "credits_credits_debits",
        "group": "CRÉDITOS",
        "subgroup": "(+)CRÉDITOS",
        "label": "(-)DÉBITOS",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits_credits_debits",
    },
    {
        "key": "credits_vacation_aid",
        "group": "CRÉDITOS",
        "subgroup": "FÉRIAS &",
        "label": "AUXÍLIOS",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits_vacation_aid",
    },
    {
        "key": "credits_adm_additional",
        "group": "CRÉDITOS",
        "subgroup": "ADM",
        "label": "ADICIONAIS",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits_adm_additional",
    },
    {
        "key": "credits_cash_eco",
        "group": "CRÉDITOS",
        "subgroup": "EM MOEDA",
        "label": "ECO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits_cash_eco",
    },

    {
        "key": "adjustments_routine_urgency_ccg",
        "group": "AJUSTES",
        "subgroup": "ROT + URG",
        "label": "CCG",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments_routine_urgency_ccg",
    },
    {
        "key": "adjustments_routine_urgency_cco",
        "group": "AJUSTES",
        "subgroup": "ROT + URG",
        "label": "CCO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments_routine_urgency_cco",
    },
    {
        "key": "adjustments_routine_urgency_ccq",
        "group": "AJUSTES",
        "subgroup": "ROT + URG",
        "label": "CCQ",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments_routine_urgency_ccq",
    },
    {
        "key": "adjustments_routine_urgency_sadt",
        "group": "AJUSTES",
        "subgroup": "ROT + URG",
        "label": "SADT",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments_routine_urgency_sadt",
    },
    {
        "key": "adjustments_routine_urgency_eco",
        "group": "AJUSTES",
        "subgroup": "ROT + URG",
        "label": "ECO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments_routine_urgency_eco",
    },
]