# Generated by Django 5.1.6 on 2025-04-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shiftsnapshot_templateshiftsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shiftsnapshot',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shiftsnapshot',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='templateshift',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='templateshift',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='templateshiftsnapshot',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='templateshiftsnapshot',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
