# Generated by Django 5.1.6 on 2025-04-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_shift_end_time_alter_shift_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='abbreviation',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
