# Generated by Django 5.1.6 on 2025-05-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_alter_center_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateshiftsnapshot',
            name='center',
        ),
        migrations.RemoveField(
            model_name='templateshiftsnapshot',
            name='month',
        ),
        migrations.RemoveField(
            model_name='templateshiftsnapshot',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShiftSnapshot',
        ),
        migrations.DeleteModel(
            name='TemplateShiftSnapshot',
        ),
    ]
