# Generated by Django 5.1.6 on 2025-05-28 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_remove_templateshiftsnapshot_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('base', 'Base'), ('original', 'Original'), ('realized', 'Realized')], max_length=10)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftsnapshots', to='shifts.center')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftsnapshots', to='shifts.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['center', 'month', 'type'], name='shifts_shif_center__90b21f_idx')],
            },
        ),
    ]
