# Generated by Django 5.1.6 on 2025-06-08 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_shiftsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='months', to=settings.AUTH_USER_MODEL),
        ),
    ]
