# Generated by Django 5.1.6 on 2025-07-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_month_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('month', 'day')},
        ),
    ]
