CONSTANTS_GRID_ROWS = [
    {"key": "period", "code": "period", "label": "Período", "editable": False,},
    {"key": "competence", "code": "competence", "label": "Competência", "editable": False,},
    {"key": "aih", "code": "aih", "label": "AIH", "editable": False,},
    {"key": "total_production", "code": "total_production", "label": "Produção Total", "editable": False,},
    {"key": "routine_production", "code": "routine_production", "label": "Produção Rotina", "editable": False,},
    {"key": "urgency_production", "code": "urgency_production", "label": "Produção Urgência", "editable": False,},
    {"key": "hour_value", "code": "hour_value", "label": "Valor Hora", "editable": False,},
    {"key": "twelve_hours", "code": "twelve_hours", "label": "12 Horas", "editable": False,},
    {"key": "routine_production_percentage", "code": "routine_production_percentage", "label": "Produção Rotina (%)", "editable": False,},
    {"key": "urgency_production_percentage", "code": "urgency_production_percentage", "label": "Produção Urgência (%)", "editable": False,},
    {"key": "routine_hour_value", "code": "routine_hour_value", "label": "Valor Hora Rotina", "editable": False,},
    {"key": "urgency_hour_value", "code": "urgency_hour_value", "label": "Valor Hora Urgência", "editable": False,},
    {"key": "twelve_hours_routine", "code": "twelve_hours_routine", "label": "12 horas Rotina", "editable": False,},
    {"key": "twelve_hours_urgency", "code": "twelve_hours_urgency", "label": "12 horas Urgência", "editable": False,},
    {"key": "billing", "code": "billing", "label": "Faturamento", "editable": False,},

    {
        "key": "charges",
        "code": "charges",
        "label": "Encargos",
        "editable": True,
        "entry_type": "debit",
    },
    {
        "key": "percentage_urgency_production",
        "code": "percentage_urgency_production",
        "label": "% Produção Urgência",
        "editable": True,
        "entry_type": "debit",
    },
    {
        "key": "reductor",
        "code": "reductor",
        "label": "Redutor",
        "editable": True,
        "entry_type": "debit",
    },
    {
        "key": "huem_hour",
        "code": "huem_hour",
        "label": "Hora HUEM",
        "editable": True,
        "entry_type": "debit",
    },
]