INPUT_GRID_COLUMNS = [
    {
        "key": "adm_hours_additional",
        "category": "ADM",
        "subcategory": "Horas",
        "label": "adicionais",
        "editable": True,
        "entry_type": "debit",
        "category_code": "adm",
        "source": "personnel",
    },

    {
        "key": "vacation_hours_rotine",
        "category": "FÉRIAS",
        "subcategory": "Horas",
        "label": "Rot",
        "editable": True,
        "entry_type": "debit",
        "category_code": "vacation",
        "source": "personnel",
    },
    {
        "key": "vacation_hours_urgent",
        "category": "FÉRIAS",
        "subcategory": "Horas",
        "label": "Urg",
        "editable": True,
        "entry_type": "debit",
        "category_code": "vacation",
        "source": "personnel",
    },

  

    # Protected Hours columns (calculated from shifts/appointments, not editable)
    {
        "key": "inhours_huem_routine_ccg",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_overtime_ccg",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_cco",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_overtime_cco",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_ccq",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_overtime_ccq",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_routine_sadt",
        "category": "HRS HUEM",
        "subcategory": "ROT",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_overtime_sadt",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },

    {
        "key": "inhours_eco_routine_eco",
        "category": "HRS ECO",
        "subcategory": "ROT",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "inhours_huem_overtime_eco",
        "category": "HRS HUEM",
        "subcategory": "URG",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },

    # Unprotected extra columns
    {
        "key": "credits_credits_debits",
        "category": "CRÉDITOS",
        "subcategory": "CRÉDITOS",
        "label": "DÉBITOS",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits",
        "source": "internal",
    },
    {
        "key": "credits_vacation_aid",
        "category": "CRÉDITOS",
        "subcategory": "FÉRIAS",
        "label": "AUXÍLIOS",
        "editable": True,
        "entry_type": "debit",
        "category_code": "credits",
        "source": "internal",
    },
    {
        "key": "credits_adm_additional",
        "category": "CRÉDITOS",
        "subcategory": "ADM",
        "label": "ADICIONAIS",
        "editable": True,
        "entry_type": "debit",
        "category_code": "credits",
        "source": "internal",
    },
    {
        "key": "credits_cash_eco",
        "category": "CRÉDITOS",
        "subcategory": "EM MOEDA",
        "label": "ECO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits",
        "source": "internal",
    },

    {
        "key": "adjustments_cash_production",
        "category": "AJUSTES",
        "subcategory": "EM MOEDA",
        "label": "PRODUÇÃO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "credits",
        "source": "internal",
    },

    {
        "key": "adjustments_routine_overtime_ccg",
        "category": "AJUSTES",
        "subcategory": "ROT+URG",
        "label": "CCG",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_overtime_cco",
        "category": "AJUSTES",
        "subcategory": "ROT+URG",
        "label": "CCO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_overtime_ccq",
        "category": "AJUSTES",
        "subcategory": "ROT+URG",
        "label": "CCQ",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_overtime_sadt",
        "category": "AJUSTES",
        "subcategory": "ROT+URG",
        "label": "SADT",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
    {
        "key": "adjustments_routine_overtime_eco",
        "category": "AJUSTES",
        "subcategory": "ROT+URG",
        "label": "ECO",
        "editable": True,
        "entry_type": "credit",
        "category_code": "adjustments",
        "source": "internal",
    },
]