INPUT_GRID_COLUMNS = [
    {
        "key": "user_name",
        "label": "ANESTESIOLOGISTA",
        "category": "",
        "editable": False,
        "kind": "text",
    },
    {
        "key": "crm",
        "label": "CRM",
        "category": "",
        "editable": False,
        "kind": "text",
    },


    {
        "key": "rp_huem_particular_proc",
        "category": "RP. HUEM",
        "subcategory": "Particular",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_convenios_proc",
        "category": "RP. HUEM",
        "subcategory": "Convênios",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_Ambulatory_proc",
        "category": "RP. HUEM",
        "subcategory": "Ambulatorial",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },
    {
        "key": "rp_huem_aih_proc",
        "category": "RP. HUEM",
        "subcategory": "AIH",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "passedover_by_huem",
        "source": "huem",
    },

    {
        "key": "individual_particular_consult",
        "category": "INDIVIDUAL",
        "subcategory": "Particular",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "individual",
        "source": "client",
    },
    {
        "key": "individual_sus_ambulatoryconsult",
        "category": "INDIVIDUAL",
        "subcategory": "SUS",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "individual",
        "source": "client",
    },

 {
        "key": "eco_particular_direct",
        "category": "R. ECO",
        "subcategory": "Particular",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_eco",
        "source": "eco",
    },
    {
        "key": "eco_unimed_coops",
        "category": "R. ECO",
        "subcategory": "Unimed",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_eco",
        "source": "eco",
    },
    {
        "key": "eco_copan_coops",
        "category": "R. ECO",
        "subcategory": "Copan",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_eco",
        "source": "eco",
    },

    {
        "key": "huem_particular_direct",
        "category": "R. HUEM",
        "subcategory": "Particular",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_huem",
        "source": "huem",
    },
    {
        "key": "huem_unimed_coops",
        "category": "R. HUEM",
        "subcategory": "Unimed",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_huem",
        "source": "huem",
    },
    {
        "key": "huem_coopan_coops",
        "category": "R. HUEM",
        "subcategory": "Copan",
        "label": "",
        "editable": True,
        "entry_type": "credit",
        "category_code": "realized_in_huem",
        "source": "huem",
    },

]