# finance/grids/summary_grid.py
SUMMARY_GRID_COLUMNS = [
    {"key": "user_name", "label": "Anestesiologista", "editable": False},
    {"key": "crm", "label": "CRM", "editable": False,},
    
    {
        "key": "individual_credits",
        "category": "",
        "subcategory": "CRÉDITOS",
        "label": "Individuais",
        "editable": False,
        "kind": "money",
    },
    {
        "key": "individual_debits",
        "category": "",
        "subcategory": "DÉBITOS",
        "label": "Individuais",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "aih_treated",
        "category": "",
        "subcategory": "AIH",
        "label": "Tratada",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "copan_reduced",
        "category": "",
        "subcategory": "Copan",
        "label": "ComRedutor",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "unimed_reduced",
        "category": "",
        "subcategory": "Unimed",
        "label": "ComRedutor",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "numberHours_routine",
        "category": "",
        "subcategory": "N_horas",
        "label": "Rot",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "numberHours_urgency",
        "category": "",
        "subcategory": "N_horas",
        "label": "Urg",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "production_divided",
        "category": "HOSPITAL",
        "subcategory": "produção",
        "label": "Dividida",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "routine_urgency_ccg",
        "category": "HOSPITAL",
        "subcategory": "ROT+URG",
        "label": "CCG",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "routine_urgency_cco",
        "category": "HOSPITAL",
        "subcategory": "ROT+URG",
        "label": "CCO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "routine_urgency_ccq",
        "category": "HOSPITAL",
        "subcategory": "ROT+URG",
        "label": "CCQ",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "routine_urgency_sadt",
        "category": "HOSPITAL",
        "subcategory": "ROT+URG",
        "label": "SADT",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "routine_urgency_eco",
        "category": "HOSPITAL",
        "subcategory": "ROT+URG",
        "label": "ECO",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "cash_total",
        "category": "HOSPITAL",
        "subcategory": "EM_MOEDA",
        "label": "TOTAL",
        "editable": False,
        "kind": "hours",
    },
    {
        "key": "cooperhec_total",
        "category": "",
        "subcategory": "COOPERHEC",
        "label": "Total",
        "editable": False,
        "kind": "hours",
    },
]